//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentThesis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalPanelistMembers
    {
        public int FinalPanelistMembersID { get; set; }
        public Nullable<int> FinalPanelistID { get; set; }
        public Nullable<int> ThesisID { get; set; }
    
        public virtual FinalPanelist FinalPanelist { get; set; }
        public virtual Thesis Thesis { get; set; }
    }
}
