//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentThesis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thesis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Thesis()
        {
            this.FinalPanelistMembers = new HashSet<FinalPanelistMembers>();
            this.PanelistMembers = new HashSet<PanelistMembers>();
            this.ThesisFiles = new HashSet<ThesisFiles>();
            this.ThesisMembers = new HashSet<ThesisMembers>();
        }
    
        public int ThesisID { get; set; }
        public Nullable<int> AuthorCategoryID { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Year { get; set; }
        public string ThesisAdviser { get; set; }
        public string ThematicArea { get; set; }
        public string TechnicalCritic { get; set; }
        public string Remarks { get; set; }
        public string Course { get; set; }
        public string Room { get; set; }
        public Nullable<System.DateTime> ScheduleDate { get; set; }
        public string FinalRoom { get; set; }
        public Nullable<System.DateTime> FinalScheduleDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> FinalApproval { get; set; }
        public Nullable<bool> IsFinished { get; set; }
        public Nullable<bool> IsArchived { get; set; }
    
        public virtual AuthorCategory AuthorCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FinalPanelistMembers> FinalPanelistMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PanelistMembers> PanelistMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThesisFiles> ThesisFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThesisMembers> ThesisMembers { get; set; }
    }
}
